fix id to reconize click, nav menu z-index and footer z-index
neomad-team/neomad.org pull request #105
Opened 2017-05-26 14:40 UTC by fuentesloic

2017-05-26 14:44 UTC, vinyll commented on static/js/utils.js
> +  const avatar = document.getElementById('avatar-img')
Are you sure? https://github.com/neomad-team/neomad.org/blob/master/templates/layout.html#L26

2017-05-26 14:45 UTC, fuentesloic commented on static/js/utils.js
> +  const avatar = document.getElementById('avatar-img')
nop nop !!!!! I make a mistake

2017-05-26 15:38 UTC, vinyll requested changes

2017-05-26 15:38 UTC, vinyll commented on templates/layout.html
> +{% include '_analytics.html' %}
You should keep the new line at the end of the file

2017-05-27 22:50 UTC, fuentesloic commented on templates/layout.html
> +{% include '_analytics.html' %}
you fix it in pro right ?

2017-05-28 12:09 UTC, vinyll commented
ok, I re-added the newline in the end of the file.
Please @fuentesloic, make sure you set your editor to always have a newline in the end of your files (this is valid for all languages / all files).

2017-05-28 12:09 UTC, vinyll approved these changes

2017-05-28 12:26 UTC, fuentesloic commented
Sorry I just check (some friends at home ...) my settings was `whitespace: false` so I change it (And I don't know why that change, a new package I think !). Anyway, I'm back with `whitespace`

2017-05-28 12:27 UTC, merged