reading time in meta
neomad-team/neomad.org pull request #111
Opened 2017-06-16 20:28 UTC by fuentesloic

2017-06-16 20:35 UTC, fuentesloic commented
Just a drop to run my mind on this way :) 
So the calcul method is not available yet

2017-06-24 21:45 UTC, vinyll approved these changes

2017-06-24 21:47 UTC, vinyll commented
Round cf: http://jinja.pocoo.org/docs/2.9/templates/#round

2017-06-24 21:49 UTC, fuentesloic commented
for exemple = {{ (document.contentlenght / 6 / 300) ||int }}

2017-06-25 14:25 UTC, vinyll requested changes

2017-06-25 14:25 UTC, vinyll commented on templates/blog/article.html
> +      <p class="reading-time">Reading time: <span>{{ (article.content|length / 6 / 250)|int }}</span> min</p>
remove quotes

2017-06-25 14:25 UTC, vinyll commented on templates/blog/macros.html
> +        <p class="reading-time">Reading time: <span>{{ (article.content|length / 6 / 250)|int }}</span> min</p>
remove quotes

2017-06-25 14:34 UTC, merged

2017-06-25 14:34 UTC, vinyll commented
We could copy Medium's style:
![screen shot 2017-06-25 at 4 32 54 pm](https://user-images.githubusercontent.com/145172/27516979-2ea9d244-59c4-11e7-83b7-d88dd192076a.png)