clean utils.js
neomad-team/neomad.org pull request #122
Opened 2017-06-28 21:12 UTC by fuentesloic

2017-06-29 08:14 UTC, vinyll requested changes
Did you check on different pages that the menu still works everywhere?

2017-06-29 08:14 UTC, vinyll commented on static/js/around-map.js
> +displayForm.forEach( button => {
Still a mistery why `.display-form` is not a form but a list of clickable buttons.
Could you rename so it's more explicit?

2017-06-29 12:04 UTC, fuentesloic commented on static/js/around-map.js
> +displayForm.forEach( button => {
because the button to open or to close have a class name `.display-form`
So I use it to toggle a class `visible`on the form
But I'll change

2017-06-29 12:05 UTC, fuentesloic commented
I test and that works

2017-07-01 15:06 UTC, vinyll commented on templates/around/map.html
> +      <button id=open-form type=button>
Why `type=button`?

2017-07-01 15:06 UTC, vinyll commented on templates/around/map.html
> +        <button id=close-form type=button>
Same question here

2017-07-02 19:33 UTC, fuentesloic commented on templates/around/map.html
> +      <button id=open-form type=button>
for nothing it's a mistake and it's useless

2017-07-02 19:33 UTC, fuentesloic commented on templates/around/map.html
> +        <button id=close-form type=button>
same mistake here

2017-07-04 12:56 UTC, merged