Home design
neomad-team/neomad.org pull request #125
Opened 2017-07-02 00:41 UTC by fuentesloic

If you are some purpose for the content don't hesitate to try a commit ;)
(of for anything else of course !!)

2017-07-02 18:28 UTC, fuentesloic commented
![first view](https://user-images.githubusercontent.com/8755623/27772544-add69ff2-5f32-11e7-850b-7c927ba1aa32.png)
![full view](https://user-images.githubusercontent.com/8755623/27772549-afbb914c-5f32-11e7-843c-e8d3f4d421b9.png)

2017-07-03 08:10 UTC, AymericFaivre commented
👍 
Good job for a first version !
I call it first version because I didn't think about it for the moment, but it looks simple, explicit, clean and nice.
Maybe you can add the latest or hotest article, it could be more attractive ?

2017-07-03 08:28 UTC, vinyll commented
Looks neat to me :)

What are the credits for the picture?
I guess we could get rid of the beta user form, and start opening the website to all.

2017-07-03 12:49 UTC, fuentesloic commented
@vinyll credit is "Reusable and modifiable"

2017-07-03 13:22 UTC, vinyll commented
License is good then. Just make sure that we shouldn't quote the author and if we must, let's add the credit.

2017-07-03 14:38 UTC, fuentesloic commented
@vinyll I need a "gate" to print the two (or more) latest articles

2017-07-03 14:41 UTC, fuentesloic commented
![capture d ecran 2017-07-03 a 10 40 03](https://user-images.githubusercontent.com/8755623/27797558-2530d2a8-5fdc-11e7-9385-964e97d4cbc6.png)
![capture d ecran 2017-07-03 a 10 40 07](https://user-images.githubusercontent.com/8755623/27797562-2751f166-5fdc-11e7-8056-eb1fa20338d6.png)

2017-07-03 14:47 UTC, vinyll commented
🚪A🚪gate🚪 ?

- _I already have an account_ is useless as we have the _login_ in the menu.
- I'd put the _Become a neomad_ button on the first main screen, with a bigger button (padding++). (@AymericFaivre would be a better suggestion for this though).
- We don't have the permission to use the picture with the guy and the computer. We should not use it for production…

2017-07-03 14:48 UTC, vinyll commented on core/views.py
> -    try:
This was redirecting the user once logged so that instead of getting to the homepage, he would land on his profile account.
Do you feel better for a authenticated user to land on the anonymous welcome page?

2017-07-03 14:48 UTC, vinyll commented on static/css/home.css
> +    top: -2em;
`rem` or `em`?
Why the comments everywhere?
I guess you could make one liners in the keyframe:
```css
@keyframes updown {
  0% {top: -8rem}
  40% {top: -8rem}
  42% {top: -2rem}
  44% {top: -8rem}
  …
```

2017-07-03 14:51 UTC, fuentesloic commented on core/views.py
> -    try:
I understand but if you want share the url of the main page you can't go there and copy it. Weird no ?

2017-07-03 14:52 UTC, fuentesloic commented
a gate to have an access to "article"

2017-07-03 14:54 UTC, vinyll commented
@fuentesloic Are you meaning a remote access to the database? It's closed for obvious security reasons.
using `docker-compose up -d` you have a local database that you can feed with articles ;)

2017-07-04 07:58 UTC, AymericFaivre commented
Like @vinyll I think you could put more padding.
You could also put it in green with no dark layer behind and maybe make it bigger.

2017-07-04 12:48 UTC, fuentesloic commented
@AymericFaivre yesterday after a conversation I tried something ... I join you the printscreen
![capture d ecran 2017-07-04 a 08 47 27-fullpage](https://user-images.githubusercontent.com/8755623/27830695-94dfe184-6095-11e7-9055-e17248990a17.png)

2017-07-04 14:44 UTC, newick commented
@fuentesloic a little bit of border radius on the content boxes?
And the same margin/padding on the articles section's top and bottom
Otherwise, that's nice!

2017-07-04 16:12 UTC, AymericFaivre commented
@fuentesloic same as @newick + I think it could be better, in the header, to have the button just under the text. And put more margin left to have a better balance in this part.
Good job 👍

2017-07-04 20:37 UTC, fuentesloic commented
@newick @AymericFaivre thinks for your feedback guys :)

2017-07-05 06:10 UTC, vinyll commented
Here's a suggestion
![screen shot 2017-07-05 at 8 08 46 am](https://user-images.githubusercontent.com/145172/27851144-3f76303a-6159-11e7-836d-38685b8bb327.png)

```css
background-color: rgba(17,195,116, 0.9);
font-size: 1.4em;
border-radius: .2em;
border: 1px solid #AFAFAF;
```

2017-07-05 12:41 UTC, fuentesloic commented
@vinyll, there my result after recommendation from @AymericFaivre, @newick 
![capture d ecran 2017-07-05 a 08 39 23-fullpage](https://user-images.githubusercontent.com/8755623/27864677-9019f522-615d-11e7-918c-1faa00a44618.png)

2017-07-05 22:48 UTC, AymericFaivre commented
Button a bit bigger, without white border and more round corner and it will be great !
Well donne @fuentesloic !
💯

2017-07-05 23:20 UTC, fuentesloic commented
I tried something with the border radius ... I'm not sure ^^
![capture d ecran 2017-07-05 a 19 17 57](https://user-images.githubusercontent.com/8755623/27888915-e3ab54ca-61b6-11e7-88fb-f26b4317e66f.png)

2017-07-06 09:39 UTC, AymericFaivre commented
Maybe you can try to make it all round?

2017-07-06 12:45 UTC, fuentesloic commented
@AymericFaivre : I can't do it because when you scroll I put the button in the header, according the place that will be weird if the button change from a square to a circle, rigth ?
![capture d ecran 2017-07-06 a 08 44 48](https://user-images.githubusercontent.com/8755623/27911574-75afd326-6227-11e7-8150-c2440c02d94b.png)

2017-07-08 18:14 UTC, AymericFaivre commented
@fuentesloic Yes, of course, I would like to say put more radius, like in this example
![firefox_screenshot_2017-07-08t18-12-57 069z](https://user-images.githubusercontent.com/2395629/27988083-2c24c3ea-6409-11e7-96e0-098fe2ffb459.png)
But your first screenshot seems to be like this so 👍

2017-07-08 18:46 UTC, fuentesloic commented
@AymericFaivre like that ?
![capture d ecran 2017-07-08 a 14 45 55](https://user-images.githubusercontent.com/8755623/27988278-3012d1a8-63ec-11e7-9d6f-863a8350cb10.png)

2017-07-08 18:50 UTC, fuentesloic commented on static/css/home.css
> +    top: -2em;
done

2017-07-08 19:39 UTC, AymericFaivre commented
@fuentesloic :1st_place_medal:

2017-07-08 21:41 UTC, fuentesloic commented
@vinyll so ... what do you think ? ;)

2017-07-14 15:49 UTC, vinyll commented
1. Section 1 is perfect to me
2. Section 2 could be improved
3. Section 3 with article: I'm not quite sure yet. I wonder if making horizontal tiles for article would not make more sense (quicker preview for a landing page).

Opinions?

2017-07-21 12:59 UTC, vinyll requested changes
The look and feels is approved to me.
Some code may be slightly improved, but I feel like we're very close :)

@AymericFaivre / @newick, any comment or suggestion?

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +let buttonPosition = (button.offsetTop - 15)
`let buttonPosition = adaptButtonPosition()`

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +  buttonPosition = (button.offsetTop - 15)
`return button.offsetTop - 15`

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +
remove empty line

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +  let diff = (event.pageY-buttonPosition)
space before and after `-`

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +    button.removeAttribute("class", "sticky");
single quotes

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +  }
You could replace these 5 lines with:

```js
button.classList.toggle('sticky', diff > 0)
```

https://developer.mozilla.org/en/docs/Web/API/Element/classList#Methods

2017-07-21 12:59 UTC, vinyll commented on static/js/home.js
> +document.addEventListener('scroll', stickyJoinButton)
this could also be on `window`

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <img src={{ url_for('static', filename='homebackground.jpg') }} alt="Nomad worker">
On a semantic perspective, is this a content image (HTML) or a decorative background (CSS)?

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <h1>N<span>e</span>omad</h1>
I guess we can remove the `span`, we haven't used it…

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      {% else %}
`{% if not current_user or not current_user.is_authenticated %}`

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +    <h2>Find out contents for nomad</h2>
_nomads_

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <a href=#features id=arrow-down></a>
This link should have some semantic content, even if hidden in css

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +    <h3>Inspire and be inspire!</h3>
_be inspired_ (and I would remove the _!_)

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <li><p>Read, write and contribute with nomad community</p></li>
_to the nomad community_

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <li><p>Follow your nomad life on your own blog and map</p></li>
_Track your nomad life on your personal map_

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <li><p>Find other nomad close to you and enjoy with them</p></li>
_other nomads nearby and share with them_

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <li><p>Find and share a place to work anywhere &amp; anytime</p></li>
_Discover and share spots where to work, wherever, whenever_

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +      <li><p>Find and share a place to work anywhere &amp; anytime</p></li>
you may remove all `li > p`

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +    <h2>Community last articles</h2>
Latest articles from nomads

2017-07-21 12:59 UTC, vinyll commented on templates/home.html
> +    <h3>Let's your discover</h3>
I would remove this, it has no purpose

2017-07-21 14:06 UTC, newick commented
what's the difference with #130?

2017-07-21 14:09 UTC, fuentesloic commented
@newick the #130 is about features only (is a branch created from here)

2017-07-21 14:12 UTC, fuentesloic commented
@vinyll your review this PR but we change feature at the #130 we should validate this one before

2017-07-25 19:10 UTC, fuentesloic commented
Ok guys, the latest screen shot :
![capture d ecran 2017-07-25 a 15 10 15-fullpage](https://user-images.githubusercontent.com/8755623/28589268-62aa9bde-714b-11e7-9203-467adc11d9b9.png)

2017-07-25 19:47 UTC, newick commented
looks nice for me, maybe too much padding in the top of the sections, I would put the same as in the bottom

2017-07-26 07:46 UTC, vinyll commented
I just noticed that the first section has the top grey banner.
We could probably blend it into the first image (transparent background).
Opinions?

2017-07-26 08:02 UTC, newick commented
or keeping it white to remain consistent with the logged interface

2017-07-26 10:30 UTC, AymericFaivre commented
Nice to me for this first release !
I think the top in white is a good solution :)

(sorry for the delay, I was high in the mountain for few days)

2017-07-26 14:52 UTC, fuentesloic commented
ok all it's done !!

2017-07-26 16:59 UTC, vinyll commented
redirecting to `/signup`: in the longer term, a user should be redirected to the page, which should itself redirect to `/signup` (with some special URL so that he sees the originally requested page once signed up).
In the meantime you may just redirect to `/signup`.

I would keep the buttons that permit to write a story. Same issue as up here. If a member is viewing the page, he should be redirected to the _new article_ page (in longer term).

2017-07-26 17:10 UTC, vinyll requested changes
We're getting very close… :)

2017-07-26 17:10 UTC, vinyll commented on static/css/home.css
> +  background-color: rgba(17,195,116, 0.8);
missing spaces after commas

2017-07-26 17:10 UTC, vinyll commented on static/css/home.css
> +  0%   { top: -7rem; }
it looks weird to move from -7rem to -5rem.
maybe you just want to move your item to `top: -5rem` and to make the movement changing another property (like `margin-top` for example)?

2017-07-26 17:10 UTC, vinyll commented on static/css/main.css
> +  color: #279e6aee;
This only works for Firefox; incompatible with other browsers.

2017-07-26 17:10 UTC, vinyll commented on static/css/main.css
> +  border: 0.125rem solid #279e6aee;
This only works for Firefox; incompatible with other browsers.

2017-07-26 17:10 UTC, vinyll commented on static/css/main.css
> +  background-color: rgba(17,195,116, 0.8);
spaces after commas

2017-07-26 17:10 UTC, vinyll commented on static/css/main.css
> +  border: 0.125rem solid rgba(17,195,116, 0.8);
same

2017-07-26 17:10 UTC, vinyll commented on templates/home.html
> +          <li>Do you know that another nomad might be in the cafe next door?</li>
Are you aware that another nomad might be in the cafe next door?

2017-08-03 13:04 UTC, fuentesloic commented
@ALL Hey guy's,
Are we good with this PR ?

2017-08-03 13:09 UTC, newick commented
from now on it's good for me ;)

2017-08-03 13:10 UTC, vinyll approved these changes

2017-08-03 13:12 UTC, newick approved these changes

2017-08-03 21:05 UTC, merged