Add basic search feature (backend)
neomad-team/neomad.org pull request #131
Opened 2017-07-18 09:18 UTC by Ydrasil

2017-07-18 13:08 UTC, vinyll requested changes
I guess the code is basic enough to be offered as a first search engine.
We may consider it and only later migrate to a search based on mongodb.

A couple of small things to fix.
A template for displaying results is missing. There's no point of merging this code if it remains unused.
Maybe @fuentesloic may be interested into pairing with you to build a page of results? May you open an issue for that?

2017-07-18 13:08 UTC, vinyll commented on search/test.py
> +    def tearDown(self):
This copy paste may mean it's time to merge some code.
You may want to create something similar to `core.Testcase` and extend it.

2017-07-18 13:08 UTC, vinyll commented on search/test.py
> +        response = self.client.get('/search/john')
We probably want to call the _GET_ with a search in a query parameters: `/search/?q=john`

2017-07-18 13:08 UTC, vinyll commented on search/test.py
> +                content='Why my french fries are cold ?').save()
remove space before _?_ ;)

2017-07-18 13:08 UTC, vinyll commented on search/views.py
> +    return json.dumps(result)
We probably want to display an actual HTML template rather than a json.

2017-07-25 09:10 UTC, vinyll requested changes

2017-07-25 09:10 UTC, vinyll commented on templates/search/list.html
> -        <li>
choose between `section > ul > li` or `section > article`. I wouldn't put `section > ul > li > article`

2017-07-25 09:10 UTC, vinyll commented on templates/search/list.html
> +        <a href='@{{ user.slug }}'>
use `{{ url_for_user(user) }}`

2017-07-25 09:10 UTC, vinyll commented on templates/search/list.html
> +        </a>
It seems like we are having this block over and over.
It might be time to make a reusable [template macro](http://jinja.pocoo.org/docs/2.9/templates/#macros) (or a reusable webcomponent).

2017-07-25 12:24 UTC, fuentesloic commented on templates/search/list.html
> +        </a>
I agree with you @vinyll but if we create a component or macro for `avatar` we should do that in an other PR

2017-07-25 12:44 UTC, vinyll requested changes

2017-07-25 12:44 UTC, vinyll commented on templates/blog/macros.html
> +  <li>
Why adding `ul > li` here? We do have a serie of articles already.

2017-07-25 12:44 UTC, vinyll commented on templates/search/list.html
> +        <a href='@{{ user.slug }}'>
use `{{ url_for_user(user) }}`

2017-07-25 12:44 UTC, vinyll commented on templates/search/list.html
> +        {{ article_list(articles=articles) }}
`article_list` inside of one `li`? You will find the list of articles in one single `<li>`

2017-07-25 12:44 UTC, vinyll commented on templates/search/list.html
> +    <h2>neomad finding</h2>
`{{users|length}} neomads found`

2017-07-25 12:44 UTC, vinyll commented on templates/search/list.html
> +  <form action='{{ url_for('search') }}' method=get>
If you use HTML quotes, use double quotes: `action="{{ url_for('search') }}"`

2017-07-25 13:49 UTC, fuentesloic commented on templates/search/list.html
> +        {{ article_list(articles=articles) }}
done

2017-07-25 13:50 UTC, fuentesloic commented on templates/search/list.html
> +  <form action='{{ url_for('search') }}' method=get>
done

2017-07-25 13:51 UTC, vinyll commented on templates/search/list.html
> +        {{ article_list(articles=articles) }}
?

2017-07-25 13:51 UTC, fuentesloic commented on templates/search/list.html
> +    <h2>neomad finding</h2>
we do the same thing for article, isn't ?

2017-07-25 13:52 UTC, vinyll commented on templates/search/list.html
> +    <h2>neomad finding</h2>
I guess so

2017-07-25 13:53 UTC, vinyll commented on templates/search/list.html
> +        {{ article_list(articles=articles) }}
Just push and it will automatically clear out these comments when they're fixed ;)

2017-07-25 13:54 UTC, fuentesloic commented on templates/blog/macros.html
> +  <li>
nop, `articles` was printing an `<articles>`, @Ydrasil fix that in the template and this morning I fix the css (but all of that are on the ydrasi/neomad repo), It's going to be good :)

2017-07-25 13:56 UTC, fuentesloic commented on templates/search/list.html
> +        <a href='@{{ user.slug }}'>
oooh that was that ^^ thx

2017-07-25 16:43 UTC, fuentesloic approved these changes
For me it's ok

2017-07-26 15:58 UTC, vinyll requested changes

2017-07-26 15:58 UTC, vinyll commented on search/test.py
> +from search.views import *
`from search import views`

2017-07-26 15:58 UTC, vinyll commented on search/test.py
> +            article.save()
Simplification:
```python
Article(title='<h1>Title</h1>',
            content='My fries are cold',
            author=user).save()
```

2017-07-26 15:58 UTC, vinyll commented on search/test.py
> +        for word in response.data.split():
`response.data` [is deprecated](http://flask.pocoo.org/docs/0.12/api/#flask.Response.data)

2017-07-26 15:58 UTC, vinyll commented on search/test.py
> +        self.assertEqual(count, 31)
You may want to replace the whole previous block (line 70 > 76) by:
```python
self.assertEqual(request.get_data().count('fries'), 31)
```

2017-07-26 15:58 UTC, vinyll commented on search/test.py
> +        self.assertEqual(count, 31)
However, it's very unclear why testing twice 10 elements make 31 (and therefore unmaintainable in the longer term for the future you or other devs).
Maybe you want to make 3 tests: one for counting the 10 `href=…fries`, another for counting the 10 others items, again for the next 10, and again for the 1.

2017-07-26 15:58 UTC, vinyll commented on templates/blog/macros.html
> +  <li>
I'm still not confident we need `ul > li > article` and not just a serie of `article`, but if you have good reasons I'll rely on you.

2017-07-26 15:58 UTC, vinyll commented on templates/search/list.html
> +        {{ article_list(articles=articles) }}
`article_list` will be replaced by `<ul><li>…</li><li>…</li><li>…</li>…</ul>`

and here we insert this whole list into a `<ul><li>REPLACED LIST</li></ul>`

Therefore, we'll result with:

```html
<ul><li>
  <ul><li>…</li><li>…</li><li>…</li>…</ul>
</li></ul>
```
View the one single `li` in the first level that will contain a list of items.

In short, we don't want the `<ul><li>` at line 42, 43, 45, 46

2017-07-26 17:17 UTC, vinyll commented
ok for me on the frontend side.
Still the backend to get fixed.

2017-07-28 14:57 UTC, Ydrasil commented on search/test.py
> +    def tearDown(self):
Do we add this improvement in this commit ?

2017-07-28 15:07 UTC, Ydrasil commented on search/test.py
> +        self.assertEqual(count, 31)
The problem is that if we want to search one user, that is actually exist, and we have one result on the app. The name that we have search will appear 3 times on the data. 
- In the URL that is in the data
- In href
- In the `<h2>`

An example with 'emailtest' below :
```
[...]
<meta property=og:url content="http://0.0.0.0:5000/search?q=searchtest">
[...]
<li class=profiles>
        <a href='/@searchtest'>
          <figure>
            <img class=avatar-img src=/static/uploads/avatars/597b51536ce8df4c77d3ac61 width=100 height=100 onerror="this.src='/static/images/avatar.png'">
          </figure>
          <h2 name=username>searchtest</h2>
        </a>
      </li>
[...]
```

I'm agree that is not very maintainable :confused:

2017-07-29 07:03 UTC, vinyll commented on search/test.py
> +        self.assertEqual(count, 31)
That's why we should not just search for "searchtest" for checking that the value exists, but search for the value in a context: `<h2 name=username>searchtest</h2>`.

2017-08-03 21:56 UTC, vinyll approved these changes

2017-08-03 21:57 UTC, merged