WIP Fix neomad tests
neomad-team/neomad.org pull request #134
Opened 2017-07-18 15:53 UTC by Ydrasil

2017-07-18 15:55 UTC, Ydrasil commented on blog/test.py
> +        self.assertEqual(result.status_code, 204)
I'm asking if the endpoint `/article/<string:id>/edit` must be a redirection or not.

2017-07-18 16:00 UTC, Ydrasil commented
Circleci still asking for a `/settings.py` file :confused:

2017-07-20 14:05 UTC, Ydrasil commented on blog/views.py
> +    return redirect(url_for_article(article))
@vinyll I have an issue with this redirection, the things is if the user remove the title of the article or the content, we don't handle the errors, I don't know how to give the errors threw this redirection.

2017-07-20 14:05 UTC, Ydrasil commented on blog/test.py
> +    '''
I have commented this tests in this WIP PR because I have an issue with the redirection in `blog/views`.

2017-07-26 16:24 UTC, vinyll requested changes

2017-07-26 16:24 UTC, vinyll commented on blog/views.py
> +        errors.append('Please, insert a title and a content')
no comma

2017-07-31 13:33 UTC, vinyll approved these changes

2017-07-31 13:33 UTC, merged