Simplify blog image cleaning
neomad-team/neomad.org pull request #143
Opened 2017-08-07 09:27 UTC by Ydrasil

@vinyll

2017-08-07 11:17 UTC, vinyll requested changes

2017-08-07 11:17 UTC, vinyll commented on blog/models.py
> +                                       self.images)]]:
This is a loop in a loop in a loop (n^3).

if you write this code before saving images in line 71 (therefore moving line 71 after this algorithm) you should retrieve the previous images with `self.images`.
Therefore you could do:

```python
for outdated_image in set(self.images) - set(images):
    os.remove(os.path.join(self.get_images_path(), outdated_image))
self.images = images
```
**untested**

2017-08-12 15:14 UTC, vinyll commented
@Ydrasil: did you check it actually work with this new version of the code? Did you see the file deleted?

2017-08-14 08:07 UTC, Ydrasil commented
Yes It's tested, the file is correctly deleted

2017-08-14 08:11 UTC, vinyll approved these changes

2017-08-14 08:11 UTC, merged