Add condition in template about user.current_location
neomad-team/neomad.org pull request #155
Opened 2017-08-17 12:26 UTC by Ydrasil

2017-08-20 19:33 UTC, vinyll requested changes
You may need to `rebased`; I see the trailing slashes are not considered here. Or did we not merge it?

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
> +    user = User(email='emailtest@test.com',
You could move this into the `setUp` of the `ArticleTest` class:
`self.user = User(…`

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
> +def login_user(self):
Move this method into the `ArticleTest` class

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
> +    self.client.post('/login', data=data, follow_redirects=True)
Add a trailing slash

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
> +                          author=create_user()).save()
`author=self.user`

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
> +        login_user(self)
`login_user(self)`? Why passing `self`??

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
> +        login_user(self)
If you move it into a method of the class it will be invalid anyways.

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
>          result = self.client.get('/article/write')
trailing slash

2017-08-20 19:33 UTC, vinyll commented on blog/test.py
>          result = self.client.get('/@emailtest/{}-{}'.format(article.slug,
trailing slash

2017-08-23 09:23 UTC, closed without merging

2017-08-23 09:25 UTC, vinyll commented
@Ydrasil: Can you give here the reason why this is closed?

2017-08-23 11:05 UTC, Ydrasil commented
I've reopen an other PR for this #159