Fix bugs from last release on dev
neomad-team/neomad.org pull request #176
Opened 2017-09-07 14:50 UTC by fuentesloic

- [ ] avatar on all page = _due to onerror missing and css erased by merge_
- [ ] default image on article = _due to image missing, erasing by db creation_
- [ ] Leaflet broke = _due to mixed active content blocked_
I have to import localy the feature

2017-09-07 21:37 UTC, vinyll requested changes

2017-09-07 21:37 UTC, vinyll commented on templates/blog/macros.html
> +        <img src="{{ article.image | default('../static/images/article.png', true) }}" width=100%>
`../static/` does not make sense. `/static/` is at the root url already.
However, `url_for('static', filename='images/article.png')` would take all its sense ;)

2017-09-08 05:26 UTC, newick commented on templates/blog/macros.html
> +        <img src={{ article.author.avatar }} width=40 height=40 onerror="this.src='{{ url_for('static', filename='images/avatar.png') }}'">
need `alt=""

2017-09-08 05:26 UTC, newick commented on templates/blog/macros.html
> +        <img src="{{ article.image | default('../static/images/article.png', true) }}" width=100%>
need `alt=""

2017-09-08 05:26 UTC, newick commented on templates/home.html
> +            <img src={{ user.avatar }} width=100 height=100 onerror="this.src='{{ url_for('static', filename='images/avatar.png') }}'">
need `alt=""

2017-09-08 05:26 UTC, newick commented on templates/layout.html
> +      <img src={{ current_user.avatar }} width=35 height=35 onerror="this.src='{{ url_for('static', filename='images/avatar.png') }}'">
guess what, need `alt="" :D

2017-09-08 05:26 UTC, newick commented on templates/user/profile.html
> +      <img name=avatar src={{ user.avatar }} width=100 height=100 onerror="this.src='{{ url_for('static', filename='images/avatar.png') }}'">
do I need to say? 😄

2017-09-08 14:51 UTC, newick commented
<img width="410" alt="capture d ecran 2017-09-08 a 16 50 00" src="https://user-images.githubusercontent.com/657454/30217243-d7f4f9c4-94b5-11e7-919e-ba0687749727.png">
When you write an article, avatar is broken (it'll be changed with styleguide but if we merge dev with master, it'll be ugly)

2017-09-08 19:18 UTC, fuentesloic commented
@newick @vinyll done!!  (from my eyes)

2017-09-08 20:59 UTC, vinyll commented on .gitignore
> +/static/dist
I don't think this should be gitignored

2017-09-09 14:42 UTC, vinyll approved these changes

2017-09-09 14:47 UTC, merged