Vuejs import styleguide - test with x-form login
neomad-team/neomad.org pull request #182
Opened 2017-09-18 16:23 UTC by fuentesloic

![capture d ecran 2017-09-18 a 12 18 46-fullpage](https://user-images.githubusercontent.com/8755623/30552484-1eac372a-9c6c-11e7-97dc-0f9c6318aabb.png)

2017-09-18 17:10 UTC, vinyll requested changes

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +form > div > label[data-v-6e1bd991] {
Nope, don't do that. The `data-v-6e1bd991` may change.

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +  <x-form class=login action={{ url_for('login') }} method=post>
for actual usage outside the demo you may want to say `<form is=x-form …>`.

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +  width: 9rem
Why do you need this BTW?

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> -    {% for error in errors %}
You still need this, don't you?

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +    <div class=form-row>
`class=form-row` is actually not required: https://github.com/neomad-team/styleguide/blob/vuejs-neomad/src/components/x-form.vue#L19

We should adapt the styleguide demo also.

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +      <input type=email name=email id=email>
`required`

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +    <input is=x-button class=primary type=submit name=login value=Login>
Why does the text look so small on your screenshot

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +<script src={{ url_for('static', filename='dist/build.js') }}></script>
This shall probably end up in the layout.
We may also want to rename it to _dist/components.js_ or something (not sure neither about a _dist_ folder for Neomad.org of _js_ folder, or elsewhere).

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +<script src={{ url_for('static', filename='dist/build.js') }}></script>
We shall probably also need a _styleguide.css_ or something.

2017-09-18 17:10 UTC, vinyll commented on templates/auth/login.html
> +<script src={{ url_for('static', filename='dist/build.js') }}></script>
be aware that components call an external css! (how should we make this dependency??): https://github.com/neomad-team/styleguide/blob/vuejs-neomad/src/components/x-form.vue#L2
Not good 🤔

2017-10-18 13:32 UTC, vinyll commented
I ❤️ed this result but I don't think we'll use it to go for css `@import`.
Should we close this PR @fuentesloic / @newick?

2017-10-19 15:11 UTC, newick commented
@vinyll if `@import`is the easiest way, i'm in

2017-10-19 15:13 UTC, vinyll commented
Closed for using native CSS instead.

2017-10-19 15:13 UTC, closed without merging