Quill editor
neomad-team/neomad.org pull request #228
Opened 2017-11-19 23:39 UTC by fuentesloic

2017-11-20 02:02 UTC, fuentesloic commented
Ok I need help now I think with python or not...

- I removed the medium editor,

2017-11-21 12:55 UTC, vinyll commented
What does Python have to do with this? JS should do that job.
Python is only saving raw data, not specific objects.

Also what do we need that Quill for the title (even without toolbars)?

2017-11-21 12:57 UTC, fuentesloic commented
Oh I see so let's go for appendChild I was thinking that python could transform it

2017-11-21 13:12 UTC, vinyll requested changes

2017-11-21 13:12 UTC, vinyll commented on docker-compose.yml
> +      - 5000:8080
❓

2017-11-21 13:12 UTC, vinyll commented on static/js/editor.js
> +var editorContent = new Quill('#editorContent', {
Use `const` unless you have a good reason. And you certainly don't here ;)

2017-11-21 13:12 UTC, vinyll commented on static/js/editor.js
> +var editorTitle = new Quill('#editorTitle')
title don't need an editor

2017-11-21 13:12 UTC, vinyll commented on static/js/editor.js
> +  form.title.value = editorTitle.getContents()
Just get the title from the `textContent` [like we did](https://github.com/neomad-team/neomad.org/pull/228/files#diff-b2eb8af5867e7d92dac4de3e62798caeL105)

2017-11-21 13:12 UTC, vinyll commented on templates/blog/article.html
> +<link href=https://cdn.quilljs.com/1.3.4/quill.bubble.css rel="stylesheet">
download it locally, and remove the quotes

2017-11-21 13:12 UTC, vinyll commented on templates/blog/article.html
> +    <h1>{{ article.title or 'Insert your title here' }}</h1>
we need [this line](https://github.com/neomad-team/neomad.org/pull/228/files#diff-b2eb8af5867e7d92dac4de3e62798caeL48) to make the title editable

2017-11-21 13:12 UTC, vinyll commented on templates/blog/article.html
> +<script src=https://cdn.quilljs.com/1.3.4/quill.js></script>
download locally ;)

2017-12-09 15:47 UTC, vinyll reviewed
Remove the word "WIP" if you expect a review ;)

2017-12-09 15:47 UTC, vinyll commented on static/css/article.css
> +h1 {
`article h1`?

2017-12-09 15:47 UTC, vinyll commented on static/js/editor.js
> +  form.title.value = title.innerHTML
`form.title.value = title.textContent` I guess, as we don't want to allow HTML in the title. (we should even clean it BTW, but later I guess)

2018-01-08 17:27 UTC, vinyll commented on templates/blog/article.html
> +  <h1 name=title>{{ article.title or 'Insert your title here' }}</h1>
remove the ending spaces

2018-02-11 16:59 UTC, closed without merging