Article edit separate
neomad-team/neomad.org pull request #252
Opened 2018-03-21 13:08 UTC by vinyll

We had an edit-in-place.
Now we have a separated page instead.

2018-03-23 12:00 UTC, fuentesloic requested changes

2018-03-23 12:00 UTC, fuentesloic commented on user/views.py
> +    return render_template('user/edit.html', user=user, articles=articles)
template `user/edit.html` doesn't exist

2018-03-23 12:00 UTC, fuentesloic commented on templates/user/profile.html
>      <nav>
you have just a link so should not we remove the `<nav>` ?

2018-03-23 12:00 UTC, fuentesloic commented on templates/user/profile.html
> +        <a class=button href={{ url_for('profile_edit') }}>Edit my profile</a>
you should user class`action-button` to keep a style (try to keep ^^)

2018-03-23 12:00 UTC, fuentesloic commented on templates/user/profile.html
> +            <a href={{ url_for('privacy') }}>Change my settings</a>
add class `action-button`

2018-03-23 12:00 UTC, fuentesloic commented on templates/user/profile.html
> +          {{ user }} disabled community mode; the contents are therefore private.<br>
remove the `<br>` use `flex-direction: column` instead

2018-03-23 12:00 UTC, fuentesloic commented on templates/user/profile.html
>          {{ user }} is currently around <a href={{ url_for_trips(user) }} data-latlng={{ user.current_location and user.current_location|join(',') }}>the world</a>.</p>
the `</p>` should be go to a next line

2018-03-23 12:00 UTC, fuentesloic commented on templates/user/profile.html
>          {{ user }} is currently around <a href={{ url_for_trips(user) }} data-latlng={{ user.current_location and user.current_location|join(',') }}>the world</a>.</p>
even the `<a>...</a>` the line is suuuuper long

2018-03-23 12:02 UTC, vinyll commented
Well, actually the whole frontend is pretty much broken.
I'm trying to clean and reset the server. Do you think you could continue this PR with the frontend @fuentesloic ?

2018-03-23 12:07 UTC, fuentesloic commented
@vinyll no prob (I hope this weekend)

2018-03-24 22:20 UTC, vinyll commented
This was replaced by #258

2018-03-24 22:20 UTC, closed without merging