create new api for login from mobile app
neomad-team/neomad.org pull request #305
Opened 2018-08-27 12:37 UTC by fuentesloic

I tried ... even not sure if I understand my own python ^^

2018-08-28 06:39 UTC, vinyll requested changes
Good job mate!

2018-08-28 06:39 UTC, vinyll commented on api/views.py
>  from flask import request, Response
`from flask import request, Response, jsonify`

2018-08-28 06:39 UTC, vinyll commented on api/views.py
> +        return Response(json.dumps(user), mimetype='application/json')
```python
    return jsonify(user)
else:
    return jsonify({'success': False})
```

2018-08-28 06:39 UTC, vinyll commented on api/views.py
> +    response = request.json
seems like you're not using this

2018-08-28 11:38 UTC, fuentesloic commented
I'm more like a child using copy/paste than python dev 😛

2018-08-28 12:11 UTC, fuentesloic commented
@vinyll thx to fix python!!!

2018-08-28 23:21 UTC, vinyll submitted a review, later dismissed

2018-08-28 23:24 UTC, vinyll approved these changes
@fuentesloic Notice that when an error occurs, a status code of 400 or 401 is returned.
When status code is 200, it means it's successful and the response contains the JSON user object :)

2018-08-29 00:11 UTC, merged

2018-08-29 00:11 UTC, fuentesloic commented
got it!