add button to re-center based on current user position
neomad-team/neomad.org pull request #60
Opened 2017-04-15 01:00 UTC by fuentesloic

that works according if the user allowed neomad to track him or not

2017-04-15 15:54 UTC, vinyll requested changes
A few syntax corrections, a question and some css selector to be more precise.
Meaning it looks great :)

2017-04-15 15:54 UTC, vinyll commented on static/css/around-map.css
> +button {
Bewarn that this selector is so generic that it will inevitability interfere with other buttons on the page.

2017-04-15 15:54 UTC, vinyll commented on templates/around/map.html
> +  <button type="button" onclick="userCenter()">
remove the quotes

2017-04-15 15:54 UTC, vinyll commented on templates/around/map.html
> +    <img height="100%" src="/static/images/recenter.png"/>
remove the quotes and the ending slash ;)
(to be consistent with the writing of the code in Neomad)

2017-04-15 15:54 UTC, vinyll commented on templates/around/map.html
> +  <button type="button" onclick="userCenter()">
`<buton type=button`?

2017-04-15 15:54 UTC, vinyll commented on static/js/around-map.js
> +userCenter = _  => {
`const userCenter =…`

2017-04-15 15:54 UTC, vinyll commented on static/js/around-map.js
> +    navigator.geolocation.getCurrentPosition(function(position) {
remove "function"

2017-04-15 15:54 UTC, vinyll commented on static/js/around-map.js
> +      currentMarker([position.coords.longitude, position.coords.latitude]);
remove semi-column

2017-04-15 15:54 UTC, vinyll commented on static/js/around-map.js
> +    });
remove semi-column

2017-04-15 15:54 UTC, vinyll commented on static/css/around-map.css
> +    right: 1em;
use `rem` instead (@newick's recommendation)

2017-04-15 15:54 UTC, vinyll commented on static/css/around-map.css
> +    margin-top: 1em;
use `rem` instead

2017-04-15 15:54 UTC, vinyll commented on static/css/around-map.css
> +    position: absolute;
Does this work well? What is it absolute to? (what is the relative parent?)

2017-04-16 14:10 UTC, vinyll requested changes
very close!

2017-04-16 14:10 UTC, vinyll commented on templates/around/map.html
> +  <button id=userCenter onclick=userCenter()>
you're gonna love it: in html and css, the convention is to use dash (-) or underscode (_).
In this project we use dash.
Therefore the id should be _user-center_ and same in the css ;)

2017-04-16 14:12 UTC, fuentesloic commented on templates/around/map.html
> +  <button id=userCenter onclick=userCenter()>
Oh I see ! thx

2017-04-16 14:18 UTC, vinyll approved these changes
🎉 🌮

2017-04-16 14:18 UTC, vinyll commented
Well, it's approved but you need to squash your commits @fuentesloic  ;)

2017-04-16 14:29 UTC, merged