Hash with to focalize in one particular point
neomad-team/neomad.org pull request #63
Opened 2017-04-17 14:04 UTC by fuentesloic

- generate an hash with the ID point when you click on share
- if hash in url, find wich point is it and move on it

2017-04-17 15:06 UTC, vinyll commented
I would suggest this icon instead: https://commons.wikimedia.org/wiki/File:Ic_my_location_48px.svg

2017-04-17 15:15 UTC, vinyll commented
I'm localized in Tanzania. Seems like _lat_ and _lng_ have been flipped.

2017-04-19 12:46 UTC, fuentesloic commented on static/js/around-map.js
>  pois.postMessage('info-requested')
if you create `const worker = new Worker('...')`, you should use `worker.postMessage('...')` isn't ? 

I changed it ;) that was to do a review to you ! mouhahahahahahahahah

2017-04-19 13:23 UTC, vinyll commented
Screenshot?

2017-04-19 13:24 UTC, fuentesloic commented
![capture d ecran 2017-04-19 a 09 23 33](https://cloud.githubusercontent.com/assets/8755623/25182227/ee40a6ea-24e1-11e7-87cc-76e746687c29.png)

2017-04-19 13:30 UTC, vinyll reviewed
I would have used _function_ to declare functions. eg: `function userCenter () {`. I feel like it's more explicit and readable that using a _const_. No big deal for now though.

Squashing the commits will be essential though for not having 11.
We'll need to consider https://www.mapbox.com/mapbox-gl-js/example/locate-user/ in a next PR

2017-04-19 13:35 UTC, vinyll requested changes

2017-04-19 13:35 UTC, vinyll commented on static/js/around-map.js
> +map.addControl(new mapboxgl.NavigationControl());
no semi-column ;)

2017-04-19 13:41 UTC, fuentesloic commented on static/js/around-map.js
> +map.addControl(new mapboxgl.NavigationControl());
done ... still bad habits

2017-04-19 13:43 UTC, vinyll requested changes

2017-04-19 13:43 UTC, vinyll commented on static/js/around-map.js
> +map.addControl(new mapboxgl.GeolocateControl());
Again, no semi-column ;)

2017-04-19 13:43 UTC, vinyll commented on static/js/around-map.js
> +            )
What is this aligned to?

2017-04-19 14:10 UTC, merged