add navigation control
neomad-team/neomad.org pull request #69
Opened 2017-04-19 14:54 UTC by fuentesloic

2017-04-19 14:55 UTC, fuentesloic commented
and now ?

2017-04-19 23:45 UTC, vinyll commented
The comment says "/around - add navigation control ", but the code does much more than that, it's also a refactoring of the previous code, and implement the hash functionality.

2017-04-19 23:46 UTC, vinyll requested changes
Let's just simplify a little the code with the comments given.
It's very not much and then let's just merge this.

2017-04-19 23:46 UTC, vinyll commented on static/js/around-map.js
> +  const hash = window.location.hash.split('#')[1]
`const hash = window.location.hash.slice(1)` seems more readable

2017-04-19 23:46 UTC, vinyll commented on static/js/around-map.js
> +      const lat = parseFloat(hashLat)
you could just write shorter:
```
const lng = parseFloat(hashData.position.longitude)
const lat = parseFloat(hashData.position.latitude)
```

2017-04-19 23:46 UTC, vinyll commented on static/js/around-map.js
> +      map.setCenter(hashCoords)
`map.setCenter([lng, lat])`

2017-04-19 23:46 UTC, vinyll commented on static/js/around-map.js
> +      map.setZoom(16)
I believed that's too zoomed. 13 seemed like a better compromise

2017-04-20 22:42 UTC, vinyll requested changes
The URL to the json file is wrong and the JS code was broken.
No chance to run in a browser ;)

2017-04-20 22:42 UTC, vinyll commented on static/js/around-map.js
> +    new mapboxgl.Marker(el, {offset:[4, -6})
`new mapboxgl.Marker(el, {offset: [4, -6]})`
A space after the comma and the closing bracket is missing

2017-04-20 22:42 UTC, vinyll commented on static/js/around-map.js
> +            )
What is this aligned to?

2017-04-20 22:42 UTC, vinyll commented on static/js/around-map.js
> +const worker = new Worker('/static/js/webworker-around.js')
Use the api, not some static file

2017-04-20 22:46 UTC, fuentesloic commented on static/js/around-map.js
> +const worker = new Worker('/static/js/webworker-around.js')
the worker grab information from the API

2017-04-20 22:49 UTC, fuentesloic commented on static/js/around-map.js
> +            )
regression ...

2017-04-20 23:12 UTC, vinyll requested changes
I all looks fine on a code perspective.
The only thing that is missing is the user pin cursor.
Right now we have a dot for the user just like the other spots

2017-04-20 23:12 UTC, vinyll commented on static/js/around-map.js
> +const worker = new Worker('/static/js/webworker-around.js')
right. I wonder if you could not use a relative import here?
`const worker = new Worker('./webworker-around.js')`

2017-04-21 12:38 UTC, fuentesloic commented on static/js/around-map.js
> +const worker = new Worker('/static/js/webworker-around.js')
Oh I see now that you mean

2017-04-21 12:43 UTC, fuentesloic commented
> Right now we have a dot for the user just like the other spots
I have a special CSS for around which overwrite yours (localize on trips.css)
So I still keep my cursor to the current user position for exemple.
I tryed to uniformize our two css into one and it's possible but maybe have juste one css file for both (like map.css) is a problem for you ?

2017-04-21 12:58 UTC, fuentesloic commented on static/js/around-map.js
> +const worker = new Worker('/static/js/webworker-around.js')
![capture d ecran 2017-04-21 a 08 58 04](https://cloud.githubusercontent.com/assets/8755623/25278389/bc69461e-2670-11e7-9965-6efc97defc6e.png)

2017-04-22 10:42 UTC, vinyll commented on static/js/around-map.js
> +const worker = new Worker('/static/js/webworker-around.js')
Well, that seems to answer that it's not possible ;)

2017-04-22 10:43 UTC, vinyll approved these changes
Seems good with me.
We will need to merge the 2 CSS files afterward.

2017-04-22 15:03 UTC, merged