Around FlyTo Hash / User
neomad-team/neomad.org pull request #82
Opened 2017-04-27 16:10 UTC by fuentesloic

2017-04-27 17:19 UTC, vinyll requested changes
You could refactor
```
map.flyTo({
    center: currentLocation,
    zoom: 11,
    bearing: 0,
    speed: 1.7,
    curve: 1
  })
```

to a function like `moveMapTo(position)` with:

```
function moveMapTo (position) {
map.flyTo({
    center: position,
    zoom: 11,
    bearing: 0,
    speed: 1.7,
    curve: 1
  })
}
```

2017-04-27 17:19 UTC, vinyll commented on static/js/around-map.js
> +if (currentLocation.length == 0) {
remove the space before the opening parenthesis

2017-04-27 17:19 UTC, vinyll commented on static/js/around-map.js
> +} else if (currentLocation.length > 0) {
remove the space before the opening parenthesis

2017-04-27 17:19 UTC, vinyll commented on static/js/around-map.js
> +    if (window.location.hash.indexOf('#') == 0) {
Why not just `if(window.location.hash)` ?
Remove the space before the opening parenthesis

2017-04-27 17:19 UTC, vinyll commented on static/js/around-map.js
> +      if (hash == el.id) {
remove space

2017-04-27 17:19 UTC, vinyll commented on static/js/around-map.js
> +const params =
Hum… ???

2017-04-27 17:21 UTC, fuentesloic commented on static/js/around-map.js
> +const params =
sorry I forget I was trying something ...

2017-04-27 17:23 UTC, fuentesloic commented
Ok for the refactoring !! i would do that but I don't find out how :')

2017-04-27 17:25 UTC, vinyll commented
>Ok for the refactoring !! i would do that but I don't find out how :')
❓

2017-04-27 17:26 UTC, vinyll commented
And please test in your browser with your browser console when you push a PR so that mistakes like `const params =` don't remain, and we review working code ;)

2017-04-27 17:27 UTC, fuentesloic commented
I can't refactor with this one 
`
map.flyTo({
      center: [poi.position.longitude, poi.position.latitude],
      zoom: 11,
      bearing: 0,
      speed: 1.7,
      curve: 1
    })
`

2017-04-27 17:29 UTC, vinyll commented
Then you can refactor with the others, right?
Why can't you refactor that one?

2017-04-27 17:32 UTC, fuentesloic commented
I can't because I have 3 differents transformation
` position => [position.coords.longitude, position.coords.latitude]
` currentLocation => currentLocation
` poi.position.longitude, poi.position.latitude]

2017-04-27 17:37 UTC, vinyll commented
ok, just try to make a:

```
function moveMap (position, somethingelse) {
  map.flyTo({stuff})
}
```

and play with that.
You should be able to do something with less repeat ;)

2017-04-27 17:41 UTC, vinyll requested changes

2017-04-27 17:41 UTC, vinyll commented on static/js/around-map.js
> +} else if(currentLocation.length > 0) {
replace your `else if(currentLocation.length > 0) {` with a `else {`

2017-04-27 17:41 UTC, vinyll commented on static/js/around-map.js
> +  const position = [position.coords.longitude, position.coords.latitude]
indent this block

2017-04-27 17:48 UTC, fuentesloic commented
what do you think now ?

2017-04-27 17:51 UTC, fuentesloic commented
what do you think now ? (I didn't do that you said ...)

2017-04-27 18:30 UTC, vinyll commented on static/js/around-map.js
> +    currentMarker(location)
What is `location`?

2017-04-27 18:31 UTC, vinyll requested changes

2017-04-27 18:31 UTC, vinyll commented on static/js/around-map.js
> +    currentMarker([position.coords.longitude, position.coords.latitude])
If you use twice the same array, you may want to store it in a variable ;)

2017-04-27 18:31 UTC, vinyll commented on static/js/around-map.js
> +    currentMarker([position.coords.longitude, position.coords.latitude])
And use it in both function

2017-04-27 18:44 UTC, fuentesloic commented on static/js/around-map.js
> +    currentMarker(location)
that was an oversight

2017-04-27 18:48 UTC, vinyll requested changes

2017-04-27 18:48 UTC, vinyll commented on static/js/around-map.js
> +    userPosition = [position.coords.longitude, position.coords.latitude]
missing a `const`

2017-04-27 18:56 UTC, vinyll approved these changes
Cool! You just need to squash your commits ;)

2017-04-27 20:04 UTC, merged

2017-04-27 20:48 UTC, vinyll commented
Hum, no… 12 commits??? 😱

2017-04-28 12:44 UTC, fuentesloic commented
we just adddone functionality: move according the hash

2017-04-28 13:55 UTC, vinyll commented
Right. I'm just confused as the PR is mentioning 12 commits and the actual master bran is just one commit with all the comments (which is less of a drama ;) )