Fix bug from /articles when there is 0 articles
neomad-team/neomad.org pull request #93
Opened 2017-05-10 15:10 UTC by Ydrasil

2017-05-10 15:12 UTC, Ydrasil commented
I haven't found another way to avoid this issue without duplicate code (like if, description or title block)

2017-05-14 21:04 UTC, vinyll requested changes

2017-05-14 21:04 UTC, vinyll commented on templates/blog/article_list.html
> +  {% block title %}Nomad articles
I guess you can wrap all the metas within `{% if articles[0] %}` `{% endif %}`.
If there's no article, there isn't much point of having them anyways.

2017-05-15 13:32 UTC, Ydrasil commented on templates/blog/article_list.html
> +  {% block title %}Nomad articles
The things is that I don't succeed to put an if around a block for not displaying it 
For instance 
```
{% block extra_og %}
    {% if articles[0] is defined %}
        <meta property=og:image content="{{ articles[0].image }}">
        <meta property=og:title content="Latest articles ({{ articles[0].title }})">
        <meta property=og:description content="{{ articles[0]|striptags|truncate(200) }}">
    {% endif %}
{% endblock %}
```
If I put the `if` around the `block extra_og` I have a bug. And its the same with other blocks.
I haven't find a way to surround all the metas with only one `{% if articles[0] %} {% endif %}`

And do you prefer `{% if articles[0] %} {% endif %}` or `{% if articles[0] is defined %} {% endif %}`?

2017-05-15 14:45 UTC, vinyll commented on templates/blog/article_list.html
> +  {% block title %}Nomad articles
`{% if articles[0] %}` is more common.

2017-05-15 14:45 UTC, vinyll commented on templates/blog/article_list.html
> +  {% block title %}Nomad articles
It may be that we can't get a _block_ inside a _if_. Good to know.

2017-05-15 14:47 UTC, vinyll commented on templates/blog/article_list.html
> +  {% block title %}Nomad articles
Here you could write:

    {% block title %}Nomad articles {% if articles[0] %} - {{ articles[0].title|truncate(40) }}{% endif %}

on one line

2017-05-15 15:30 UTC, Ydrasil commented on templates/blog/article_list.html
> +  {% block title %}Nomad articles
Done :wink:

2017-05-15 15:35 UTC, vinyll requested changes

2017-05-15 15:35 UTC, vinyll commented on templates/blog/article_list.html
> +    Hotest article is « {{ articles[0].title }} ».
`{% if articles[0] %}Hotest article is « {{ articles[0].title }} ».{% endif %}`

2017-05-19 22:05 UTC, vinyll requested changes

2017-05-19 22:05 UTC, vinyll commented on templates/blog/article_list.html
> +  {% if articles[0] %} Hotest article is « {{ articles[0].title }} ».{% endif %}
the `{%.endblock %}` for the block description should be here

2017-05-19 22:05 UTC, vinyll commented on templates/blog/article_list.html
>  {% endblock %}
the block extra_og should not be embedded into the block description.

2017-05-21 22:59 UTC, Ydrasil commented
@vinyll My bad about the embedded `block extra_og`, its good now :+1:

2017-05-22 11:56 UTC, vinyll approved these changes

2017-05-22 11:57 UTC, merged