Add privacy page and trip deletion
neomad-team/neomad.org pull request #95
Opened 2017-05-11 09:41 UTC by Ydrasil

I don't know if its a good idea to put the privacy's link page at the left of the logout button.

2017-05-14 21:14 UTC, vinyll requested changes
Please change the `import json`.
We could approve the PR then.
However we do really need written tests to prove users we actually delete the data.
If you don't feel like taking the written test I can make it. It may be another commit anyways (it could even be a commit before this one, and this one fixing the tests).

2017-05-14 21:14 UTC, vinyll commented on templates/user/privacy.html
> +      <button class="button delete">Delete</button></form></td>
`<button class=button…>`?

2017-05-14 21:14 UTC, vinyll commented on user/views.py
> +from json import loads
just use `import json`. a method `loads` is a too generic name, we always import json and call function onto the module.

2017-05-14 21:14 UTC, vinyll commented on user/views.py
> +def privacy_delete_trip(location, date):
Did you hand test it? Does it work?

2017-05-24 15:49 UTC, Ydrasil commented on user/views.py
> +def privacy_delete_trip(location, date):
I have hand test it, and its working, but I'll made some test

2017-05-25 06:20 UTC, vinyll commented on user/views.py
> +def privacy_delete_trip(location, date):
That would be awesome for sure!
For the rest it's all good with me 👍

2017-06-15 16:19 UTC, vinyll requested changes

2017-06-15 16:19 UTC, vinyll commented on templates/user/privacy.html
> +      date: '{{ location.date|datetime }}',
You may want to insert this into a JS `new Date()` and format it

2017-06-15 16:19 UTC, vinyll commented on trips/test.py
> +    def test_trip_same_area_under_10_km(self):
👍

2017-06-19 14:56 UTC, Ydrasil commented
@vinyll

2017-07-01 15:35 UTC, vinyll requested changes
Sorry for long delay for review @Ydrasil.
Some url/method things to improve for deleting a ressource.

@fuentesloic might be interested into this feature and adding features to this frontend ;)

2017-07-01 15:35 UTC, vinyll commented on user/test.py
> +        url = '/privacy/[10, 10]/' + user.locations[0]\
Ideally I would use the timestamp that is more url-friendly and unique enough:
```python
url = '/privacy/{}'.format(user.location[0].date.timestamp())
```

However, if for some reason you could not do that, at least formatting the url a little cleaner:

```python
url = '/privacy/10,10/{}'.format(user.location[0].date.strftime('%Y-%m-%d %H:%M:%S.%f'))
```

But really the first way may be more appropriate

2017-07-01 15:35 UTC, vinyll commented on user/test.py
> +        result = self.client.post(url, content_type='application/json')
`.post()` that is actually deleting is confusing.
We probably want to do a `.delete()`.
If for some reason you couldn't (eg: you're using a form), you should have `/delete` in your url.

2017-07-01 15:35 UTC, vinyll commented on user/test.py
> +        self.assertEqual(result.status_code, 200)
Does it return something in the body? If not it should return a `204`

2017-07-01 15:35 UTC, vinyll commented on user/views.py
> +def privacy_delete_trip(location, date):
`methods` should allow delete.
URL could be improved with just a timestamp (see previous comment).

2017-07-12 06:34 UTC, vinyll approved these changes

2017-07-17 14:52 UTC, merged