Fix bug that appear if the title or the content is empty
neomad-team/neomad.org pull request #97
Opened 2017-05-15 14:18 UTC by Ydrasil

2017-05-19 22:09 UTC, vinyll reviewed
This is a very good point.
However, how do these error desplay to the client? Are they displayed in the error banner or does it just break the server to the client (like an error 500)?

2017-05-21 22:46 UTC, Ydrasil commented
When the content is empty, its a server error `500`. Its because of the language detection that is trying to know what is the language is used in an empty content. After that the article appear correctly in the user's home page and we can correctly edit him. However the article doesn't seem to appear in `/articles`
When the title is empty, we can correctly save the article, he stay in the database, but we can't edit him. When we try to edit him (click on the article in the user's home page) a 404 error is appearing, and like the other bug above, the article doesn't seem to appear in `/articles`

2017-05-22 12:07 UTC, vinyll commented
I undestand that when there is no title or content, the server renders an error 500 when trying to display the article. Hence this PR makes sense.

However, my question is more on a user perspective. When the user is trying to save an article with no title or no content, he should see his article with an error message explaining that he must enter a title or a content to save his article.

I feel like `abort(400…)` would just display a crash page that is not helpful for the user. What if he had written an article and forgot the title? He should see his content again and say something like "Your article should have a title".

2017-06-02 11:12 UTC, Ydrasil commented
@vinyll What do you think about the error message now ?

2017-06-03 07:54 UTC, vinyll requested changes

2017-06-03 07:54 UTC, vinyll commented on blog/views.py
> +import langdetect
why adding `langdetect` for the empty title or content?

2017-06-03 07:54 UTC, vinyll commented on blog/views.py
> +from .models import Article, clean_html
`clean_html` is a good point! 👍

2017-06-03 07:54 UTC, vinyll commented on blog/views.py
> +            return render_template('blog/article.html', article=article,
A more conventional way to pass errors to a template is a variable called `errors` [like here](https://github.com/neomad-team/neomad.org/blob/master/auth/views.py#L28).

+1 for the _400_ status 👍

2017-06-03 07:54 UTC, vinyll commented on blog/views.py
> +                               edit=True, empty=True), 400
same here with the `errors`

2017-06-03 07:54 UTC, vinyll commented on templates/blog/article.html
> +  {% if empty %}
If you use `errors` as a list of errors, we could even extract [the specific errors rendering template portion](https://github.com/neomad-team/neomad.org/blob/master/templates/auth/login.html#L65) to move it into an [includable/reusable template portion](http://jinja.pocoo.org/docs/2.9/templates/#include)

2017-07-01 16:16 UTC, vinyll approved these changes

2017-07-01 16:16 UTC, merged