Add test language detection
neomad-team/neomad.org pull request #98
Opened 2017-05-16 08:33 UTC by Ydrasil

2017-05-19 22:13 UTC, vinyll requested changes

2017-05-19 22:13 UTC, vinyll commented on blog/test.py
> +        self.assertTrue(article.language == 'fr')
use `self.assertEqual`

2017-05-19 22:13 UTC, vinyll commented on blog/test.py
> +        self.assertTrue(article.language == 'en')
Same here

2017-05-19 22:13 UTC, vinyll commented on blog/test.py
> +        article = Article(title='A title in english',
Capital _e_ in English ;)

2017-05-19 22:13 UTC, vinyll commented on blog/test.py
> +                                  'english</p>').save()
Same _E_

2017-05-21 22:22 UTC, Ydrasil commented
@vinyll Done :+1:

2017-05-22 12:10 UTC, vinyll approved these changes

2017-05-22 12:10 UTC, merged